### ISSUE TITLE
missing info in documentation

### ISSUE THREAD

**Issue by tomse** [sharpninja/CBM-Command#1]
Sorry for creating this as an issue, I didn't know how else to contact you.

I've been going through the documentation and haven't found who makes this software.

as in a group name, real name or company etc.. 
I'd also like to see dates in docs of release.

all for historical purpose/easier to find rather than starting up the program

cheers
Tomse

**Comment by sharpninja** [comment]
At the very bottom of the documentation is the attributions.  Did you need something more specific?

**Comment by tomse** [comment]
I was looking for a scene group name, team name or something to singularize "Payton Byrd and Greg King" 

and of course a release notes or version file which has the release date of any given release.

cheers
Tomse

**Comment by sharpninja** [comment]
The releases and dates are on the old site. Cbmcommand.codeplex.com

There was no group involved.  On the releases page on github is a document detailing the creation of Cbmcommand

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
